providers:
  openai:
    default_model: "gpt-4o-mini"
    default_max_tokens: 1000
  anthropic:
    default_model: "claude-3-haiku-20240307"
    default_max_tokens: 1000

server:
  grpc_port: 50051
  http_port: 8080
