services:
  ai-router:
    build: .
    expose:
      - "8080"
      - "50051"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GRPC_PORT=50051
      - HTTP_PORT=8080
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
    deploy:
      replicas: 3

  load-balancer:
    image: nginx:latest
    ports:
      - "80:80" # HTTP
      - "8000:8000" # gRPC
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-router

volumes:
  config-store:
