# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import grpc.experimental
import warnings

import ai_router_pb2 as ai__router__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_router_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AIRouterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteRequest = channel.unary_unary(
                '/ai_router.AIRouter/RouteRequest',
                request_serializer=ai__router__pb2.AIRequest.SerializeToString,
                response_deserializer=ai__router__pb2.AIResponse.FromString,
                _registered_method=True)
        self.StreamingRouteRequest = channel.unary_stream(
                '/ai_router.AIRouter/StreamingRouteRequest',
                request_serializer=ai__router__pb2.AIRequest.SerializeToString,
                response_deserializer=ai__router__pb2.AIResponse.FromString,
                _registered_method=True)


class AIRouterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RouteRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamingRouteRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIRouterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteRequest,
                    request_deserializer=ai__router__pb2.AIRequest.FromString,
                    response_serializer=ai__router__pb2.AIResponse.SerializeToString,
            ),
            'StreamingRouteRequest': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamingRouteRequest,
                    request_deserializer=ai__router__pb2.AIRequest.FromString,
                    response_serializer=ai__router__pb2.AIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_router.AIRouter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_router.AIRouter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIRouter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RouteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_router.AIRouter/RouteRequest',
            ai__router__pb2.AIRequest.SerializeToString,
            ai__router__pb2.AIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamingRouteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_router.AIRouter/StreamingRouteRequest',
            ai__router__pb2.AIRequest.SerializeToString,
            ai__router__pb2.AIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
