"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AIRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ParametersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    PROVIDER_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    PROMPT_FIELD_NUMBER: builtins.int
    MAX_TOKENS_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    provider: builtins.str
    model: builtins.str
    prompt: builtins.str
    max_tokens: builtins.int
    @property
    def parameters(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        provider: builtins.str = ...,
        model: builtins.str = ...,
        prompt: builtins.str = ...,
        max_tokens: builtins.int = ...,
        parameters: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["max_tokens", b"max_tokens", "model", b"model", "parameters", b"parameters", "prompt", b"prompt", "provider", b"provider"]) -> None: ...

global___AIRequest = AIRequest

@typing.final
class AIResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_FIELD_NUMBER: builtins.int
    PROVIDER_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    content: builtins.str
    provider: builtins.str
    model: builtins.str
    def __init__(
        self,
        *,
        content: builtins.str = ...,
        provider: builtins.str = ...,
        model: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "model", b"model", "provider", b"provider"]) -> None: ...

global___AIResponse = AIResponse
